<?xml version="1.0" encoding="utf-8"?>
<xml><main readme="main">&lt;table cellspacing="0" class="table1"&gt;&#13;
	&lt;tr&gt;&#13;
		&lt;td&gt;&lt;a href="?ThisDir={$webdir}&amp;amp;title=返回到主目录" class="red"&gt;返回主目录&lt;/a&gt; | 当前目录：{$thisdir} | 空间: {$filesize}&lt;/td&gt;&#13;
		&lt;td&gt;&lt;a href="?ThisDir={$updir}"&gt;&lt;font color='ff0000'&gt;↑上一目录&lt;/font&gt;&lt;/a&gt;&lt;/td&gt;&#13;
	&lt;/tr&gt;&#13;
	&lt;tr&gt;&#13;
		&lt;td colspan='2'&gt;&#13;
			&lt;form method="post" action="?act=upfile&amp;amp;filepath={$thisdir}" enctype="multipart/form-data" style="display:inline;"&gt;&#13;
			&lt;input type="file" name="file1" size="20" /&gt; &lt;input type="submit" class="uploadbutton" id="uploadbutton" value="上传文件" /&gt;&#13;
			&lt;/form&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&#13;
&#13;
			&lt;form method="post" action="?act=creatdir&amp;amp;filepath={$thisdir}" style="display:inline;"&gt;&#13;
			&lt;input type="text" name="dirname" value="" size="15" maxlength="20" /&gt; &#13;
			&lt;input type="submit" value="新建文件夹" /&gt;	&#13;
			&lt;/form&gt;&#13;
		&lt;/td&gt;&#13;
	&lt;/tr&gt;&#13;
&lt;/table&gt;&#13;
&#13;
&lt;br /&gt;&#13;
&#13;
&lt;table cellspacing="0" class="table1 j_list"&gt;&#13;
	 &lt;tr&gt;&#13;
	  &lt;th width="*"&gt;文件/文件夹名&lt;/th&gt;&#13;
	  &lt;th width="120"&gt;文件大小&lt;/th&gt;&#13;
	  &lt;th width="180"&gt;最后修改时间&lt;/th&gt;&#13;
	  &lt;th width="150"&gt;操作&lt;/th&gt;&#13;
	 &lt;/tr&gt;&#13;
	 {$lifolder}&#13;
	 {$lifile}&#13;
&lt;/table&gt;</main><css readme="css"></css><li readme="li">&lt;tr&gt;&#13;
	&lt;td class="ico"&gt;&lt;a href="{$href}" class="{$filetype}"&gt;{$title}&lt;/a&gt;&lt;/td&gt;&#13;
	&lt;td&gt;{$size}&lt;/td&gt;&#13;
	&lt;td&gt;{$time}&lt;/td&gt;&#13;
	&lt;td&gt;{$operate}&lt;/td&gt;&#13;
&lt;/tr&gt;</li><formedit readme="formedit">&lt;div class="pxbig"&gt;&#13;
	&lt;div class="th"&gt;{$filepath}&lt;/div&gt;&#13;
	&lt;form method="post" action="{$action}" id="myform" class="ac"&gt;&#13;
		&lt;textarea id="content" name="content" style="width:95%;" cols="100" rows="35"&gt;{$content}&lt;/textarea&gt;&#13;
&#13;
		&lt;p&gt;&lt;/p&gt;&#13;
		&#13;
		&lt;input type="button" value="提交" id="submit" class="submit1" onclick="j_repost('myform')" /&gt; Ctrl+s 快速保存&#13;
	&lt;/form&gt;&#13;
&lt;/div&gt;&#13;
&#13;
&#13;
&lt;script type="text/javascript"&gt;&#13;
&lt;!--&#13;
$(document).ready(function(){&#13;
&#13;
		$("#content").bind('keydown', function(event){&#13;
			var obj=$(this).attr("id");&#13;
			if (event.ctrlKey&amp;&amp;83==event.keyCode)&#13;
			{&#13;
				$("#submit").click();&#13;
				return(false);&#13;
			}&#13;
		})&#13;
&#13;
		$("#content").keydown(function(event){&#13;
			if (9==event.keyCode)&#13;
			{&#13;
				$(this).insertAtCaret("	");&#13;
				return false;&#13;
			};&#13;
		});&#13;
&#13;
})&#13;
//--&gt;&#13;
&lt;/script&gt;</formedit></xml>
