<?xml version="1.0" encoding="utf-8"?>
<xml><myform readme="myform">&lt;form method="post" action="{$action}" name="myform" id="myform"&gt;&#13;
  &lt;table class="table1" cellspacing="0"&gt;&#13;
    &lt;tr&gt;&#13;
      &lt;td width="80"&gt;频道名称:&lt;cite&gt;*&lt;/cite&gt;&lt;/td&gt;&#13;
      &lt;td width="*"&gt;&#13;
			&lt;input type="text" name="title" id="title" value="{$title}" size="40" /&gt;&#13;
			&amp;nbsp;简称:&lt;input type="text" name="cha_unit" id="cha_unit" value="{$cha_unit}" size="10" /&gt;&#13;
			&amp;nbsp;编码:&lt;input type="text" name="ic" id="ic" value="{$ic}" size="20" /&gt;&lt;span class="gray"&gt;没有可以不填&lt;/span&gt;&#13;
		&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
    &lt;tr&gt;&#13;
      &lt;td&gt;频道目录:&lt;cite&gt;*&lt;/cite&gt;&lt;/td&gt;&#13;
      &lt;td&gt;&#13;
			&lt;input type="text" name="cha_dir" id="cha_dir" value="{$cha_dir}"  size="20" /&gt;&#13;
			&amp;nbsp; 模块: &lt;input type="text" name="cha_modulename" value="{$cha_modulename}" /&gt;&#13;
			&amp;nbsp; 关联数据表: &lt;input type="text" name="cha_mdb" value="{$cha_mdb}" size="20" /&gt;&lt;span class="gray"&gt;用逗号分隔,不需要带表前缀&lt;/span&gt;&#13;
		&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
	 &lt;tr&gt;&#13;
      &lt;td&gt;频道提示:&lt;/td&gt;&#13;
      &lt;td&gt;&lt;input type="text" name="mytip" id="mytip" value="{$mytip}"  class="inputtext" /&gt;&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
	 &lt;tr style="display:none"  id="linecopystyle"&gt;&#13;
      &lt;td&gt;复制模板:&lt;/td&gt;&#13;
      &lt;td&gt;&#13;
			&lt;input type="checkbox" name="copystyle" value="1" /&gt; 原频道模板复制到新的频道&#13;
		&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
	 &lt;tr&gt;&#13;
      &lt;td&gt;模板目录:&lt;/td&gt;&#13;
      &lt;td&gt;&lt;input type="text" name="cha_style" id="cha_style" value="{$cha_style}" class="inputtext" /&gt;&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
    &lt;tr&gt;&#13;
      &lt;td&gt;频道介绍:&lt;br /&gt;支持Html&lt;/td&gt;&#13;
      &lt;td&gt;&lt;textarea name="readme" id="readme" rows="2" cols="48" class="inputtext"&gt;{$readme_htmlencode}&lt;/textarea&gt;&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
    &lt;tr&gt;&#13;
      &lt;td&gt;预览图:&lt;/td&gt;&#13;
      &lt;td&gt;&#13;
			&lt;input type="text" name="preimg" id="preimg" value="{$preimg}"  class="inputtext2" /&gt;&amp;nbsp;&#13;
			&lt;a href="{$selimg}" class="j_open"&gt;&lt;img src="images/view.gif" title="浏览服务器" alt="view" class="vmiddle" /&gt;&lt;/a&gt;&#13;
		&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
    &lt;tr&gt;&#13;
      &lt;td&gt;Title:&lt;/td&gt;&#13;
      &lt;td&gt;&lt;input type="text" name="mytitle" id="mytitle" value="{$mytitle}" class="inputtext" /&gt;&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
    &lt;tr&gt;&#13;
      &lt;td&gt;Keywords:&lt;/td&gt;&#13;
      &lt;td&gt;&lt;input type="text" name="mykeywords" id="mykeywords" value="{$mykeywords}" class="inputtext" /&gt;&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
    &lt;tr&gt;&#13;
      &lt;td&gt;Description:&lt;/td&gt;&#13;
      &lt;td&gt;&lt;textarea name="mydescription" id="mydescription" rows="2" cols="48" class="inputtext"&gt;{$mydescription}&lt;/textarea&gt;&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
    &lt;tr id="chaopen"&gt;&#13;
		&lt;td&gt;其它&lt;/td&gt;&#13;
      &lt;td&gt;&#13;
			类型:&lt;input type="text" name="mytype" id="mytype" value="{$mytype}" size="10" /&gt;  &amp;nbsp;&#13;
			&lt;select name="cha_opentype" id="cha_opentype"&gt;&#13;
				&lt;option&gt;打开方式&lt;/option&gt;&#13;
          &lt;option value="1"&gt;新窗口&lt;/option&gt;&#13;
          &lt;option value="0"&gt;原窗口&lt;/option&gt;&#13;
        &lt;/select&gt;&#13;
      &#13;
      &amp;nbsp;&lt;select name="cha_show" id="cha_show"&gt;&#13;
			&lt;option&gt;是否显示&lt;/option&gt;&#13;
          &lt;option value="1"&gt;显示&lt;/option&gt;&#13;
          &lt;option value="0"&gt;不显示&lt;/option&gt;&#13;
      &lt;/select&gt;       &#13;
		&#13;
	   &amp;nbsp;&lt;select name="isuse" id="isuse"&gt;&#13;
			&lt;option&gt;使用:&lt;/option&gt;&#13;
          &lt;option value="1"&gt;使用&lt;/option&gt;&#13;
          &lt;option value="0"&gt;不使用&lt;/option&gt;&#13;
        &lt;/select&gt;&#13;
		&#13;
		&amp;nbsp;排序:&lt;input type="text" name="cls" id="cls" size="3" value="{$cls}" /&gt;&#13;
&#13;
		&amp;nbsp;记录数/页:&lt;input type="text" name="cha_page" id="cha_page" value="{$cha_page}" size="3" /&gt;&#13;
		&lt;/td&gt;&#13;
    &lt;/tr&gt;&#13;
&#13;
	 &lt;tr&gt;&#13;
		&lt;td&gt;&amp;nbsp;&lt;/td&gt;&#13;
		&lt;td&gt;&lt;input type="button" name="submit" class="submit" value="保 存" onclick="j_post('myform')" /&gt;&lt;/td&gt;&#13;
	 &lt;/tr&gt;&#13;
&#13;
  &lt;/table&gt;&#13;
&#13;
&lt;/form&gt;&#13;
&#13;
&#13;
&#13;
&lt;script type="text/javascript"&gt;&#13;
&lt;!--&#13;
$(document).ready(function(){&#13;
	$("#cha_opentype").val("{$cha_opentype}");&#13;
	$("#cha_show").val("{$cha_show}");&#13;
	$("#isuse").val("{$isuse}");&#13;
	$("#icanghost").val("{$icanghost}");&#13;
&#13;
	{$js}&#13;
})	&#13;
//--&gt;&#13;
&lt;/script&gt;</myform><css readme="css"></css></xml>
